version: '3.8'

services:
  # Сервер API
  api:
    build: .
    container_name: flower-shop-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=flower_shop
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=${JWT_SECRET:-your_secret_key}
      - JWT_EXPIRES_IN=24h
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-your_bot_token}
      - TELEGRAM_SECRET=${TELEGRAM_SECRET:-your_telegram_secret}
    volumes:
      - ./uploads:/app/uploads

  # Фронтенд (Mini App)
  client:
    build: ../flower-shop-app
    container_name: flower-shop-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api

  # База данных
  db:
    image: postgres:14-alpine
    container_name: flower-shop-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flower_shop
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/config/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  pgdata: